defaults:
  -
    scope:
      path: ""
    values:
      layout: "collection"
      title: "Documentation"
collections:
  app:
    output: true
  packages:
    output: true
  # desktop:
  #   output: true
  # web:
  #   output: true
  # ios:
  #   output: true
  # android:
  #   output: true
