defaults:
  -
    scope:
      path: ""
    values:
      layout: "collection"
      title: "Treehub"
collections:
  packages:
    output: true
    description: "Packages o stuff"
  # desktop:
  #   output: true
  # web:
  #   output: true
  # ios:
  #   output: true
  # android:
  #   output: true
